### ISSUE TITLE
Move migration on start up in main.go for goinventory api

### ISSUE THREAD

**Issue by Quasaer** [Quasaer/inventory#5]
Currently, the migration as part of the deployment workflow action pulls down the go-migrate cli and runs the migrate command before the deployment to faasd. In order for this to work, I need to have a public endpoint to my postgres instance. I can do this with inlets pro but I think it will be more simpler if I had the migrations happen on startup in the application after the database connection is made. 

The benefits of this would be:
- I will have one less VPS on DigitalOcean to pay for.
- I will not be required to use all three of my inlets If I want to host my application to support a staging and prod environment since two of them will be required for the postgres DBs which means that I use it for other things in the future.
- May cut down on ci/cd pipeline total time. I noticed that the go-migrate command step takes a while because it is pulling down a shell script to install the cli. This step can be cut out completely.

**Comment by Quasaer** [comment]
Getting issues with the migration directory when deploying to openfaas/faasd. It cannot find the directory. Has something to do with the dockerfile I suspect.

**Comment by Quasaer** [comment]
I am a bit confused. The dockerfile copies the contents of goinventory-api to the work dir /go/src/handler/. Adding a RUN ls line in the dockerfile shows that the migration directory has been copied over but that pathing doesn't exist when deployed.

**Comment by Quasaer** [comment]
Ah, okay. I think I get it now. go build outputs the contents to /handler/handler. This wouldn't include the migrations folder. I'll need to use go embed feature to add in that directory so it can be used when it is built.

**Comment by Quasaer** [comment]
No idea why, but I am getting this 
2022/04/04 23:38:38 no change
exit status 1
For the migrations. I reverted the changes to what is was before where the migrations were working but it is throwing this.

**Comment by Quasaer** [comment]
I have a resolution in place. I needed to change the dockerfile to target multi arch builds to arm. I thought I had this but I needed to tweek it a little

**Comment by Quasaer** [comment]
I need to double check with the migrations first. The migration for the test table is failing.

**Comment by rwx-yxu** [comment]
Resolved. There was a stray comma in the test migration file.
